export interface Currency {
    code: string;
    name: string;
    symbol: string;
    flag: string;
    country: string;
}

export const CURRENCIES: Currency[] = [
    { code: 'USD', name: 'US Dollar', symbol: '$', flag: '🇺🇸', country: 'United States' },
    { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺', country: 'European Union' },
    { code: 'GBP', name: 'British Pound', symbol: '£', flag: '🇬🇧', country: 'United Kingdom' },
    { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪', country: 'UAE' },
    { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', flag: '🇦🇫', country: 'Afghanistan' },
    { code: 'ALL', name: 'Albanian Lek', symbol: 'L', flag: '🇦🇱', country: 'Albania' },
    { code: 'AMD', name: 'Armenian Dram', symbol: '֏', flag: '🇦🇲', country: 'Armenia' },
    { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', flag: '🇨🇼', country: 'Curaçao/Sint Maarten' },
    { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', flag: '🇦🇴', country: 'Angola' },
    { code: 'ARS', name: 'Argentine Peso', symbol: '$', flag: '🇦🇷', country: 'Argentina' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', flag: '🇦🇺', country: 'Australia' },
    { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', flag: '🇦🇼', country: 'Aruba' },
    { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', flag: '🇦🇿', country: 'Azerbaijan' },
    { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', flag: '🇧🇦', country: 'Bosnia and Herzegovina' },
    { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', flag: '🇧🇧', country: 'Barbados' },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', flag: '🇧🇩', country: 'Bangladesh' },
    { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', flag: '🇧🇬', country: 'Bulgaria' },
    { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', flag: '🇧🇭', country: 'Bahrain' },
    { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', flag: '🇧🇮', country: 'Burundi' },
    { code: 'BMD', name: 'Bermudan Dollar', symbol: '$', flag: '🇧🇲', country: 'Bermuda' },
    { code: 'BND', name: 'Brunei Dollar', symbol: '$', flag: '🇧🇳', country: 'Brunei' },
    { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', flag: '🇧🇴', country: 'Bolivia' },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', flag: '🇧🇷', country: 'Brazil' },
    { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', flag: '🇧🇸', country: 'Bahamas' },
    { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', flag: '🇧🇹', country: 'Bhutan' },
    { code: 'BWP', name: 'Botswana Pula', symbol: 'P', flag: '🇧🇼', country: 'Botswana' },
    { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', flag: '🇧🇾', country: 'Belarus' },
    { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', flag: '🇧🇿', country: 'Belize' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', flag: '🇨🇦', country: 'Canada' },
    { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', flag: '🇨🇩', country: 'DR Congo' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', flag: '🇨🇭', country: 'Switzerland' },
    { code: 'CLP', name: 'Chilean Peso', symbol: '$', flag: '🇨🇱', country: 'Chile' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳', country: 'China' },
    { code: 'COP', name: 'Colombian Peso', symbol: '$', flag: '🇨🇴', country: 'Colombia' },
    { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', flag: '🇨🇷', country: 'Costa Rica' },
    { code: 'CUP', name: 'Cuban Peso', symbol: '$', flag: '🇨🇺', country: 'Cuba' },
    { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', flag: '🇨🇻', country: 'Cape Verde' },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿', country: 'Czechia' },
    { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', flag: '🇩🇯', country: 'Djibouti' },
    { code: 'DKK', name: 'Danish Krone', symbol: 'kr', flag: '🇩🇰', country: 'Denmark' },
    { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', flag: '🇩🇴', country: 'Dominican Republic' },
    { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', flag: '🇩🇿', country: 'Algeria' },
    { code: 'EGP', name: 'Egyptian Pound', symbol: '£', flag: '🇪🇬', country: 'Egypt' },
    { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', flag: '🇪🇷', country: 'Eritrea' },
    { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', flag: '🇪🇹', country: 'Ethiopia' },
    { code: 'FJD', name: 'Fijian Dollar', symbol: '$', flag: '🇫🇯', country: 'Fiji' },
    { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', flag: '🇫🇰', country: 'Falkland Islands' },
    { code: 'GEL', name: 'Georgian Lari', symbol: '₾', flag: '🇬🇪', country: 'Georgia' },
    { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', flag: '🇬🇭', country: 'Ghana' },
    { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', flag: '🇬🇮', country: 'Gibraltar' },
    { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', flag: '🇬🇲', country: 'Gambia' },
    { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', flag: '🇬🇳', country: 'Guinea' },
    { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', flag: '🇬🇹', country: 'Guatemala' },
    { code: 'GYD', name: 'Guyanaese Dollar', symbol: '$', flag: '🇬🇾', country: 'Guyana' },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$', flag: '🇭🇰', country: 'Hong Kong' },
    { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', flag: '🇭🇳', country: 'Honduras' },
    { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', flag: '🇭🇷', country: 'Croatia' },
    { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', flag: '🇭🇹', country: 'Haiti' },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺', country: 'Hungary' },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩', country: 'Indonesia' },
    { code: 'ILS', name: 'Israeli New Sheqel', symbol: '₪', flag: '🇮🇱', country: 'Israel' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳', country: 'India' },
    { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', flag: '🇮🇶', country: 'Iraq' },
    { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', flag: '🇮🇷', country: 'Iran' },
    { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', flag: '🇮🇸', country: 'Iceland' },
    { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', flag: '🇯🇲', country: 'Jamaica' },
    { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', flag: '🇯🇴', country: 'Jordan' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵', country: 'Japan' },
    { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪', country: 'Kenya' },
    { code: 'KGS', name: 'Kyrgystani Som', symbol: 'с', flag: '🇰🇬', country: 'Kyrgyzstan' },
    { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', flag: '🇰🇭', country: 'Cambodia' },
    { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', flag: '🇰🇲', country: 'Comoros' },
    { code: 'KPW', name: 'North Korean Won', symbol: '₩', flag: '🇰🇵', country: 'North Korea' },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩', flag: '🇰🇷', country: 'South Korea' },
    { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', flag: '🇰🇼', country: 'Kuwait' },
    { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', flag: '🇰🇾', country: 'Cayman Islands' },
    { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', flag: '🇰🇿', country: 'Kazakhstan' },
    { code: 'LAK', name: 'Laotian Kip', symbol: '₭', flag: '🇱🇦', country: 'Laos' },
    { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', flag: '🇱🇧', country: 'Lebanon' },
    { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', flag: '🇱🇰', country: 'Sri Lanka' },
    { code: 'LRD', name: 'Liberian Dollar', symbol: '$', flag: '🇱🇷', country: 'Liberia' },
    { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', flag: '🇱🇸', country: 'Lesotho' },
    { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', flag: '🇱🇾', country: 'Libya' },
    { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', flag: '🇲🇦', country: 'Morocco' },
    { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', flag: '🇲🇩', country: 'Moldova' },
    { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', flag: '🇲🇬', country: 'Madagascar' },
    { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', flag: '🇲🇰', country: 'North Macedonia' },
    { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', flag: '🇲🇲', country: 'Myanmar' },
    { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', flag: '🇲🇳', country: 'Mongolia' },
    { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', flag: '🇲🇴', country: 'Macau' },
    { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', flag: '🇲🇷', country: 'Mauritania' },
    { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', flag: '🇲🇺', country: 'Mauritius' },
    { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', flag: '🇲🇻', country: 'Maldives' },
    { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', flag: '🇲🇼', country: 'Malawi' },
    { code: 'MXN', name: 'Mexican Peso', symbol: '$', flag: '🇲🇽', country: 'Mexico' },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾', country: 'Malaysia' },
    { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', flag: '🇲🇿', country: 'Mozambique' },
    { code: 'NAD', name: 'Namibian Dollar', symbol: '$', flag: '🇳🇦', country: 'Namibia' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬', country: 'Nigeria' },
    { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', flag: '🇳🇮', country: 'Nicaragua' },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴', country: 'Norway' },
    { code: 'NPR', name: 'Nepalese Rupee', symbol: 'रू', flag: '🇳🇵', country: 'Nepal' },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', flag: '🇳🇿', country: 'New Zealand' },
    { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', flag: '🇴🇲', country: 'Oman' },
    { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', flag: '🇵🇦', country: 'Panama' },
    { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', flag: '🇵🇪', country: 'Peru' },
    { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', flag: '🇵🇬', country: 'Papua New Guinea' },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱', flag: '🇵🇭', country: 'Philippines' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', flag: '🇵🇰', country: 'Pakistan' },
    { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', flag: '🇵🇱', country: 'Poland' },
    { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', flag: '🇵🇾', country: 'Paraguay' },
    { code: 'QAR', name: 'Qatari Rial', symbol: 'ر.ق', flag: '🇶🇦', country: 'Qatar' },
    { code: 'RON', name: 'Romanian Leu', symbol: 'lei', flag: '🇷🇴', country: 'Romania' },
    { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', flag: '🇷🇸', country: 'Serbia' },
    { code: 'RUB', name: 'Russian Ruble', symbol: '₽', flag: '🇷🇺', country: 'Russia' },
    { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', flag: '🇷🇼', country: 'Rwanda' },
    { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', flag: '🇸🇦', country: 'Saudi Arabia' },
    { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', flag: '🇸🇧', country: 'Solomon Islands' },
    { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', flag: '🇸🇨', country: 'Seychelles' },
    { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', flag: '🇸🇩', country: 'Sudan' },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪', country: 'Sweden' },
    { code: 'SGD', name: 'Singapore Dollar', symbol: '$', flag: '🇸🇬', country: 'Singapore' },
    { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', flag: '🇸🇭', country: 'Saint Helena' },
    { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', flag: '🇸🇱', country: 'Sierra Leone' },
    { code: 'SOS', name: 'Somali Shilling', symbol: 'S', flag: '🇸🇴', country: 'Somalia' },
    { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', flag: '🇸🇷', country: 'Suriname' },
    { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', flag: '🇸🇸', country: 'South Sudan' },
    { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', flag: '🇸🇹', country: 'São Tomé and Príncipe' },
    { code: 'SVC', name: 'Salvadoran Colón', symbol: '$', flag: '🇸🇻', country: 'El Salvador' },
    { code: 'SYP', name: 'Syrian Pound', symbol: '£', flag: '🇸🇾', country: 'Syria' },
    { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', flag: '🇸🇿', country: 'Eswatini' },
    { code: 'THB', name: 'Thai Baht', symbol: '฿', flag: '🇹🇭', country: 'Thailand' },
    { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', flag: '🇹🇯', country: 'Tajikistan' },
    { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', flag: '🇹🇲', country: 'Turkmenistan' },
    { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', flag: '🇹🇳', country: 'Tunisia' },
    { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', flag: '🇹🇴', country: 'Tonga' },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷', country: 'Turkey' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', flag: '🇹🇹', country: 'Trinidad and Tobago' },
    { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', flag: '🇹🇼', country: 'Taiwan' },
    { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', flag: '🇹🇿', country: 'Tanzania' },
    { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', flag: '🇺🇦', country: 'Ukraine' },
    { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', flag: '🇺🇬', country: 'Uganda' },
    { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', flag: '🇺🇾', country: 'Uruguay' },
    { code: 'UZS', name: 'Uzbekistan Som', symbol: 'so\'m', flag: '🇺🇿', country: 'Uzbekistan' },
    { code: 'VEF', name: 'Venezuelan Bolívar', symbol: 'Bs.F.', flag: '🇻🇪', country: 'Venezuela' },
    { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', flag: '🇻🇳', country: 'Vietnam' },
    { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', flag: '🇻🇺', country: 'Vanuatu' },
    { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', flag: '🇼🇸', country: 'Samoa' },
    { code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA', flag: '🇨🇲', country: 'Central Africa' },
    { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', flag: '🇦🇬', country: 'East Caribbean' },
    { code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'CFA', flag: '🇸🇳', country: 'West Africa' },
    { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', flag: '🇾🇪', country: 'Yemen' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: '🇿🇦', country: 'South Africa' },
    { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', flag: '🇿🇲', country: 'Zambia' },
    { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '$', flag: '🇿🇼', country: 'Zimbabwe' },
];

export const formatCurrency = (amount: number, currencyCode: string = 'USD') => {
    const currency = CURRENCIES.find(c => c.code === currencyCode) || CURRENCIES[0];
    try {
        const formatted = new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: currencyCode,
            minimumFractionDigits: 2,
            maximumFractionDigits: 2
        }).format(amount);
        return formatted;
    } catch (e) {
        return `${currency.symbol}${amount.toFixed(2)}`;
    }
};
